Tet 94/right toolbar
3d-diploma-project/tetrahedron-desktop pull request #16
Opened 2024-11-15 19:15 UTC by GurgenAvagyan

- Create class `RightToolbar`
- Add class `ToggleSwitch` for displaying toggle switch

![image](https://github.com/user-attachments/assets/2b3ef813-bfe0-491b-a65c-267a0991f209)

2024-11-15 19:31 UTC, VadimST04 approved these changes

2024-11-16 16:22 UTC, HappyMary16 requested changes

2024-11-16 16:22 UTC, HappyMary16 commented on src/main/java/org/cmps/tetrahedron/config/WindowProperties.java
> +    static {
this may be done without static block

2024-11-16 16:22 UTC, HappyMary16 commented on src/main/java/org/cmps/tetrahedron/config/WindowProperties.java
> +    static {
if you add comments, do it in English

2024-11-16 16:22 UTC, HappyMary16 commented on src/main/java/org/cmps/tetrahedron/utils/Utils.java
> +public class Utils {
And what is this utils class doing?
Let's give it more descriptive name

2024-11-19 17:48 UTC, HappyMary16 approved these changes

2024-11-20 16:15 UTC, ut5tw approved these changes
please resolve conflicts

2024-11-20 17:48 UTC, merged