TET-152 Fix bug with location of coordinates info
3d-diploma-project/tetrahedron-desktop pull request #20
Opened 2024-12-16 21:13 UTC by GurgenAvagyan

https://github.com/user-attachments/assets/fedb1459-4c15-4ee5-b347-f2e24bc39154

2024-12-16 21:31 UTC, HappyMary16 requested changes

2024-12-16 21:31 UTC, HappyMary16 commented on src/main/java/org/cmps/tetrahedron/controller/SceneController.java
> +//        absolutePane.getStyleClass().add("absolute-pane");
Do we need these commented lines?

2024-12-17 23:01 UTC, HappyMary16 approved these changes

2024-12-18 05:24 UTC, VadimST04 approved these changes

2024-12-18 16:10 UTC, merged